namespace PicoSwitch.ControllerLink.Host
{
    [default_interface]
    runtimeclass ControllerLinkTask : Windows.ApplicationModel.Background.IBackgroundTask
    {
        ControllerLinkTask();
    }
}
