namespace PicoSwitch.Management.Tests;

/// <summary>
/// Locates the repository's shared fixtures by walking up from the test binary.
///
/// The fixtures are NOT copied into the test project. A copy is a second
/// authority, and the whole point of <c>tools/fixtures/</c> is that C, Kotlin and
/// C# read the SAME file — a one-sided edit has to fail somewhere, and it cannot
/// if each language keeps its own snapshot.
/// </summary>
public static class RepositoryFixtures
{
    public static string Path(string relativePath)
    {
        var cursor = new DirectoryInfo(AppContext.BaseDirectory);
        while (cursor is not null)
        {
            var candidate = System.IO.Path.Combine(cursor.FullName, relativePath);
            if (File.Exists(candidate))
            {
                return candidate;
            }

            cursor = cursor.Parent;
        }

        throw new FileNotFoundException(
            $"Cannot find {relativePath} above {AppContext.BaseDirectory}");
    }

    public static string ReadText(string relativePath) => File.ReadAllText(Path(relativePath));

    public const string ManagementProtocolFixture = "tools/fixtures/management/protocol-v1.json";

    /// <summary>
    /// Exact KB/M replies produced by the real firmware formatters, generated by
    /// tools/test_ns2_kbm_commands.c.
    /// </summary>
    /// <remarks>
    /// Hand-written fixtures are how a pagination bug passed every client test
    /// while the adapter dropped a row per page: the fixtures encoded the same
    /// misunderstanding the firmware did. These bytes come from the firmware
    /// itself, so a client that reconstructs them completely is a client that
    /// works against the adapter.
    /// </remarks>
    public const string KbmWireCorpus = "tools/fixtures/management/kbm-wire-corpus.json";

    /// <summary>
    /// Amiibo crypto vectors, generated from the Kotlin implementation over real
    /// tags by <c>AmiiboCryptoFixtureTool</c>.
    /// </summary>
    /// <remarks>
    /// The reason a THIRD implementation of this algorithm is tolerable at all.
    /// Its failure mode is silent — a wrong HMAC produces a tag the console
    /// simply rejects, with nothing to read — so the C# port is only trustworthy
    /// to the extent it reproduces these. Carries no key material: the key set is
    /// named by fingerprint, and the tag bytes are read from the dumps the
    /// vectors point at.
    /// </remarks>
    public const string AmiiboCryptoVectors = "tools/fixtures/amiibo/crypto-vectors.json";
    public const string ControllerLinkFaceMapping = "tools/fixtures/controller_link_face_mapping.csv";
    public const string BridgeReportGoldens = "tools/fixtures/bridge_report_goldens.csv";
    public const string BridgeDescriptorHeader = "tools/fixtures/android_controller_hid.h";
}
