package dev.picoswitch.management

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The fingerprint this app computes must equal the one the FIRMWARE computes.
 *
 * It is the only thing that can answer "is the adapter's copy the one I have?"
 * across two companions that share no profile ids, so a divergence here does not
 * fail loudly — it silently reports every profile as out of date, or worse,
 * reports a stale resident copy as current.
 *
 * The vectors are generated by tools/test_ns2_kbm_commands.c from the real
 * `ns2_kbm_fingerprint`, not written by hand. That matters: an earlier version
 * of this code fed managed ENUM ORDINALS into the hash instead of the firmware's
 * numeric codes, which is exactly the class of mistake a hand-written fixture
 * would have encoded twice and never caught.
 */
class KbmFingerprintParityTest {

    private val corpus = Json.parseToJsonElement(
        checkNotNull(javaClass.getResource("/kbm-wire-corpus.json")).readText(),
    ).jsonObject

    private data class Vector(
        val label: String,
        val layout: KbmProfile,
        val overrides: List<KbmBinding>,
        val mouse: KbmMouseConfig,
        val expected: Long,
    )

    private val vectors = corpus["fingerprints"]!!.jsonArray.map { element ->
        val item = element.jsonObject
        val mouse = item["mouse"]!!.jsonObject
        Vector(
            label = item["label"]!!.jsonPrimitive.content,
            layout = checkNotNull(KbmProfile.fromWire(item["layout"]!!.jsonPrimitive.content)),
            overrides = item["overrides"]!!.jsonArray.map { row ->
                val binding = row.jsonObject
                KbmBinding(
                    source = checkNotNull(
                        KbmSource.parse(binding["src"]!!.jsonPrimitive.content),
                    ),
                    destination = checkNotNull(
                        KbmDestination.fromWire(binding["dst"]!!.jsonPrimitive.content),
                    ),
                    custom = true,
                )
            },
            mouse = KbmMouseConfig(
                sensitivityX = mouse["sensitivityX"]!!.jsonPrimitive.int,
                sensitivityY = mouse["sensitivityY"]!!.jsonPrimitive.int,
                velocityWindowMs = mouse["velocityWindowMs"]!!.jsonPrimitive.int,
                invertX = mouse["invertX"]!!.jsonPrimitive.boolean,
                invertY = mouse["invertY"]!!.jsonPrimitive.boolean,
                antiDeadzone = mouse["antiDeadzone"]!!.jsonPrimitive.int,
            ),
            expected = item["fingerprint"]!!.jsonPrimitive.long,
        )
    }

    @Test fun `every firmware vector reproduces exactly`() {
        assertTrue("no fingerprint vectors in the corpus", vectors.isNotEmpty())
        vectors.forEach { vector ->
            assertEquals(
                vector.label,
                vector.expected,
                KbmFingerprint.compute(vector.layout, vector.overrides, vector.mouse),
            )
        }
    }

    @Test fun `canonical form makes override order irrelevant`() {
        // Canonicalisation is what lets two companions that built the same
        // mapping in a different order agree that they hold the same profile.
        // compute() deliberately does NOT sort for its caller: the firmware
        // hashes the stored order, so a silent re-sort here would hide a caller
        // that had passed a genuinely non-canonical set.
        val vector = vectors.first { it.overrides.size > 1 }
        assertEquals(
            vector.expected,
            KbmFingerprint.compute(
                vector.layout,
                KbmFingerprint.canonical(vector.overrides.reversed()),
                vector.mouse,
            ),
        )
    }

    @Test fun `canonical drops nothing a user chose and keeps not-mapped`() {
        // "This key does nothing" is a real override that differs from the
        // layout default, so it must survive canonicalisation and reach the hash.
        val none = KbmBinding(
            KbmSource(KbmSourceKind.Key, 0x04), KbmDestination.None, custom = true,
        )
        assertEquals(listOf(none), KbmFingerprint.canonical(listOf(none)))
        assertNotEquals(
            KbmFingerprint.compute(KbmProfile.Keyboard, emptyList(), KbmMouseConfig()),
            KbmFingerprint.compute(KbmProfile.Keyboard, listOf(none), KbmMouseConfig()),
        )
    }

    @Test fun `the two layouts fingerprint differently with identical content`() {
        // The layout is part of the identity: the same overrides mean different
        // things in a keyboard-only bank and a keyboard-and-mouse one, and a hash
        // that ignored it would let one claim the other's resident position.
        val overrides = listOf(
            KbmBinding(KbmSource(KbmSourceKind.Key, 0x04), KbmDestination.A, custom = true),
        )
        val mouse = KbmMouseConfig()
        assertNotEquals(
            KbmFingerprint.compute(KbmProfile.Keyboard, overrides, mouse),
            KbmFingerprint.compute(KbmProfile.KeyboardMouse, overrides, mouse),
        )
    }

    @Test fun `mouse tuning is part of the identity`() {
        val overrides = emptyList<KbmBinding>()
        assertNotEquals(
            KbmFingerprint.compute(
                KbmProfile.KeyboardMouse, overrides, KbmMouseConfig(sensitivityX = 512),
            ),
            KbmFingerprint.compute(
                KbmProfile.KeyboardMouse, overrides, KbmMouseConfig(sensitivityX = 1024),
            ),
        )
    }
}
