package dev.picoswitch.management

import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The KB/M read path, driven by the EXACT bytes the real firmware emits.
 *
 * The Android mirror of the Windows page-bootstrap test, against the same
 * corpus: tools/fixtures/management/kbm-wire-corpus.json, generated by
 * tools/test_ns2_kbm_commands.c from src/ns2_kbm_commands.c for a worst-case
 * adapter (full profile library, maximum-length names, every override slot bound
 * to the longest destination name).
 *
 * This exists because hand-written fixtures are how a pagination bug passed every
 * client test in two languages while the adapter dropped a row per page: the
 * fixtures encoded the same misunderstanding the firmware did. Bytes from the
 * firmware itself cannot do that.
 */
class KbmWireCorpusTest {

    private val corpus = Json.parseToJsonElement(
        checkNotNull(javaClass.getResource("/kbm-wire-corpus.json")).readText(),
    ).jsonObject

    private val replyMaxBytes = corpus["replyMaxBytes"]!!.jsonPrimitive.int

    private data class Reply(val label: String, val command: String, val bytes: Int, val json: String)

    private val replies = corpus["replies"]!!.jsonArray.map { element ->
        val item = element.jsonObject
        Reply(
            label = item["label"]!!.jsonPrimitive.content,
            command = item["command"]!!.jsonPrimitive.content,
            bytes = item["bytes"]!!.jsonPrimitive.int,
            json = item["reply"]!!.toString(),
        )
    }

    @Test fun `every firmware reply fits the wireless slot`() {
        // The limit travels WITH the corpus, from the firmware's own constant, so
        // this cannot drift from the value the adapter actually enforces. The
        // first defect in this area was a test asserting against a
        // firmware-local 2048-byte buffer instead of the wire.
        assertTrue("corpus is empty", replies.isNotEmpty())
        replies.forEach { reply ->
            assertTrue(
                "${reply.command} is ${reply.bytes} bytes, limit is $replyMaxBytes",
                reply.bytes <= replyMaxBytes,
            )
        }
    }

    @Test fun `each realized mapping reconstructs completely from the real bytes`() = runTest {
        for (layout in listOf(KbmProfile.Keyboard, KbmProfile.KeyboardMouse)) {
            val label = "map-${layout.wire}"
            val pages = replies.filter { it.label == label }
            assertTrue("$label missing from the corpus", pages.isNotEmpty())
            assertTrue(
                "$label fit in one reply; this test is not covering a boundary",
                pages.size > 1,
            )

            val channel = ScriptedCorpusChannel(pages.associate { it.command to it.json })
            val mapping = ManagementClient(channel).loadKbmMapping(layout)

            // The expectation comes from the firmware's own `total`, not from a
            // number this test made up. The shipped bug was precisely a short
            // mapping that every other check accepted.
            val total = Json.parseToJsonElement(pages.first().json)
                .jsonObject["total"]!!.jsonPrimitive.int
            assertEquals("$label reconstructed short", total, mapping.bindings.size)

            // No duplicates: a cursor that failed to advance would repeat rows and
            // could still reach the right count if it also skipped some.
            val sources = mapping.bindings.map { it.source.wire }
            assertEquals("$label has duplicate sources", sources.size, sources.toSet().size)

            // And every source the adapter actually sent survived the parser.
            val emitted = pages.flatMap { page ->
                Json.parseToJsonElement(page.json).jsonObject["bindings"]!!.jsonArray.map {
                    it.jsonObject["src"]!!.jsonPrimitive.content
                }
            }
            assertEquals("$label lost a source in the parser", emitted.sorted(), sources.sorted())
        }
    }

    @Test fun `the profile library reconstructs completely from the real bytes`() = runTest {
        val pages = replies.filter { it.label == "profiles" }
        assertTrue("the corpus must span multiple profile replies", pages.size > 1)

        val script = pages.associate { it.command to it.json }.toMutableMap()
        replies.filter { it.label == "active" }.forEach { script[it.command] = it.json }

        val profiles = ManagementClient(ScriptedCorpusChannel(script)).kbmProfiles()

        val total = Json.parseToJsonElement(pages.first().json)
            .jsonObject["total"]!!.jsonPrimitive.int
        assertEquals(total, profiles.profiles.size)
        assertEquals(KbmLimits.MAX_PROFILES, profiles.max)
        assertTrue(profiles.supported)
        // Both layouts report what they are really running.
        assertTrue(profiles.activeFor(KbmProfile.Keyboard) != null)
        assertTrue(profiles.activeFor(KbmProfile.KeyboardMouse) != null)
    }

    @Test fun `a stored profile's mapping reconstructs completely`() = runTest {
        val pages = replies.filter { it.label == "pmap" }
        assertTrue("pmap missing from the corpus", pages.isNotEmpty())

        val first = Json.parseToJsonElement(pages.first().json).jsonObject
        val info = KbmProfileInfo(
            id = first["profileId"]!!.jsonPrimitive.int,
            layout = KbmProfile.fromWire(first["profile"]!!.jsonPrimitive.content)!!,
            name = "corpus",
            revision = 1,
            overrides = 0,
            fingerprint = 0,
        )

        val channel = ScriptedCorpusChannel(pages.associate { it.command to it.json })
        val mapping = ManagementClient(channel).loadKbmProfileMapping(info)

        assertEquals(first["total"]!!.jsonPrimitive.int, mapping.bindings.size)
    }
}

/**
 * Answers by command rather than in sequence: the walk decides its own order from
 * each reply's `next`, and pinning an order here would test the fixture instead
 * of the client.
 */
private class ScriptedCorpusChannel(
    private val replies: Map<String, String>,
) : ManagementChannel {
    override suspend fun transact(command: String, timeoutMillis: Long): String =
        replies[command] ?: error("no corpus reply for '$command'")
}
