using System.Text.Json;
using PicoSwitch.Companion.Services.Presentation;
using PicoSwitch.Management;
using Xunit;

namespace PicoSwitch.Companion.Services.Tests;

/// <summary>
/// The whole Keyboard and Mouse page bootstrap, driven by the EXACT bytes the
/// real firmware emits.
/// </summary>
/// <remarks>
/// THIS IS THE TEST THAT SHOULD HAVE EXISTED. Two defects reached hardware while
/// every unit test passed:
///
///   1. <c>kbm status</c> outgrew the wireless reply slot. Its test asserted
///      against a firmware-local 2048-byte buffer instead of the wire limit.
///   2. Mapping pagination combined a fixed <c>page * PAGE_SIZE</c> offset with a
///      variable, byte-budgeted row count, so every page silently dropped its
///      last row. The client fixtures were hand-written from the same
///      misunderstanding, so they agreed with the bug.
///
/// Both were invisible because nothing exercised the real firmware output through
/// the real client. The replies here are generated by
/// tools/test_ns2_kbm_commands.c from src/ns2_kbm_commands.c, for a worst-case
/// adapter: a full profile library, maximum-length names, and every override slot
/// bound to the longest destination name. If the firmware's wire format changes,
/// this test consumes the new bytes on the next host-suite run and fails here
/// rather than on the user's desk.
/// </remarks>
public sealed class KeyboardMousePageBootstrapTests
{
    private const string Address = "AA:BB:CC:DD:EE:01";

    [Fact]
    public async Task TheRealFirmwareCorpusLoadsToReadyWithBothMappingsComplete()
    {
        using var fixture = new ConnectionServiceFixture();
        await fixture.RememberAdapterAsync(Address);
        var corpus = KbmWireCorpus.Load();
        corpus.Script(fixture.Transport);

        var state = await fixture.Service.RefreshKeyboardMouseAsync();

        // 1. READY. Not "loaded enough to draw something".
        Assert.Equal(KeyboardMouseReadiness.Ready, state.Readiness);
        Assert.Equal(string.Empty, state.Fault);
        Assert.Equal(CapabilityState.Available, state.Capability);

        // 2. COMPLETE RECONSTRUCTION, checked against the firmware's own `total`
        // rather than against a number this test made up. The failure that
        // shipped was precisely a short mapping that every other check accepted.
        foreach (var layout in KbmLayouts.All)
        {
            var mapping = state.Mapping(layout);
            var expected = corpus.TotalFor(layout);
            Assert.True(mapping.Loaded, $"{layout} did not load");
            Assert.Equal(expected, mapping.Bindings.Count);

            // No duplicates: a cursor that failed to advance would repeat rows
            // and still reach the right count if it also skipped some.
            var sources = mapping.Bindings.Select(b => b.Source.Wire).ToList();
            Assert.Equal(sources.Count, sources.Distinct().Count());

            // And nothing the adapter sent went missing on the way through the
            // parser: the corpus knows every source it emitted for this layout.
            Assert.Equal(corpus.SourcesFor(layout).OrderBy(s => s, StringComparer.Ordinal),
                         sources.OrderBy(s => s, StringComparer.Ordinal));
        }

        // 3. The profile library came back whole, over more than one reply.
        Assert.True(corpus.ProfileReplies > 1,
                    "the corpus must span multiple profile replies or this proves nothing");
        Assert.Equal(corpus.ProfileTotal, state.Profiles.Profiles.Count);
        Assert.Equal(6, state.Profiles.Max);
        Assert.True(state.Profiles.Supported);

        // 4. Both layouts report what they are really running.
        foreach (var layout in KbmLayouts.All)
        {
            Assert.NotNull(state.Profiles.ActiveFor(layout));
        }

        // 5. No reply the firmware produced exceeds the wire slot. The corpus
        // carries the firmware's own limit, so this cannot drift from it.
        Assert.All(corpus.Replies,
                   reply => Assert.True(reply.Bytes <= corpus.ReplyMaxBytes,
                                        $"{reply.Command} is {reply.Bytes} bytes"));
    }

    [Fact]
    public async Task TheProjectedPageShowsTheProfileWorkflowAndNoLegacyFallback()
    {
        using var fixture = new ConnectionServiceFixture();
        await fixture.RememberAdapterAsync(Address);
        KbmWireCorpus.Load().Script(fixture.Transport);

        var state = await fixture.Service.RefreshKeyboardMouseAsync();
        var view = KeyboardMouse.Project(state, KbmLayout.Keyboard, connected: true,
                                         draft: null);

        Assert.Equal(KeyboardMouseReadiness.Ready, view.Readiness);
        Assert.True(view.ShowEditor);
        Assert.True(view.ProfilesSupported);

        // The workflow the page must expose: a Default that cannot be deleted,
        // the user's own profiles, and a selection that is not an application.
        Assert.Contains(view.Profiles, row => row.Builtin);
        Assert.Contains(view.Profiles, row => !row.Builtin);
        Assert.NotNull(view.SelectedProfile);
        Assert.NotNull(view.ActiveMapping);
        Assert.Empty(view.NotReadyTitle);
    }

    [Fact]
    public async Task AnAdapterMissingARequiredCommandAsksForAFirmwareUpdate()
    {
        // NOT a fallback. Pre-profile firmware is not a supported configuration
        // for this build, and pretending otherwise is what produced a page that
        // looked unfinished instead of out of date.
        using var fixture = new ConnectionServiceFixture();
        await fixture.RememberAdapterAsync(Address);
        KbmWireCorpus.Load().Script(fixture.Transport);
        fixture.Transport.Replies.Remove("kbm profiles 0");
        fixture.Transport.Failures["kbm profiles 0"] =
            new AdapterCommandException("kbm profiles 0", null, "unknown command");

        var state = await fixture.Service.RefreshKeyboardMouseAsync();

        Assert.Equal(KeyboardMouseReadiness.FirmwareUpdateRequired, state.Readiness);
        Assert.Contains("kbm profiles 0", state.Fault);
        Assert.False(state.Loaded);

        var view = KeyboardMouse.Project(state, KbmLayout.Keyboard, connected: true,
                                         draft: null);
        Assert.False(view.ShowEditor);
        Assert.False(view.ProfilesSupported);
        Assert.Equal("Firmware update required", view.NotReadyTitle);
    }

    [Fact]
    public async Task AShortenedMappingPageIsReportedAsIncompleteWithDetail()
    {
        // The exact defect that shipped, injected: a reply that stops early but
        // advances the cursor as if it had not. The client must refuse it AND say
        // enough for the next person to identify it without a hardware session.
        using var fixture = new ConnectionServiceFixture();
        await fixture.RememberAdapterAsync(Address);
        var corpus = KbmWireCorpus.Load();
        corpus.Script(fixture.Transport);
        fixture.Transport.Replies["kbm map kb 0"] =
            """{"profile":"kb","profileId":0,"cursor":0,"total":26,"bindings":[{"src":"key:1A","dst":"lstick_up","custom":false}],"next":8}""";

        var state = await fixture.Service.RefreshKeyboardMouseAsync();

        Assert.Equal(KeyboardMouseReadiness.Error, state.Readiness);
        // `next` must equal cursor + rows. A stride that skips is refused at the
        // parser, before it can become a short mapping nobody can explain.
        Assert.False(string.IsNullOrWhiteSpace(state.Fault));

        var view = KeyboardMouse.Project(state, KbmLayout.Keyboard, connected: true,
                                         draft: null);
        Assert.False(view.ShowEditor);
        Assert.Equal("The adapter's reply could not be used", view.NotReadyTitle);
        Assert.Contains(state.Fault, view.NotReadyDetail);
    }
}

/// <summary>
/// Reads tools/fixtures/management/kbm-wire-corpus.json and scripts a transport
/// with it, plus the status/counters/mouse replies the page also needs.
/// </summary>
internal sealed class KbmWireCorpus
{
    internal sealed record Reply(string Label, string Command, int Bytes, string Json);

    public required IReadOnlyList<Reply> Replies { get; init; }

    public required int ReplyMaxBytes { get; init; }

    public static KbmWireCorpus Load()
    {
        var text = ReadRepositoryFile("tools/fixtures/management/kbm-wire-corpus.json");
        using var document = JsonDocument.Parse(text);
        var root = document.RootElement;
        var replies = new List<Reply>();
        foreach (var element in root.GetProperty("replies").EnumerateArray())
        {
            replies.Add(new Reply(
                element.GetProperty("label").GetString()!,
                element.GetProperty("command").GetString()!,
                element.GetProperty("bytes").GetInt32(),
                element.GetProperty("reply").GetRawText()));
        }

        return new KbmWireCorpus
        {
            Replies = replies,
            ReplyMaxBytes = root.GetProperty("replyMaxBytes").GetInt32(),
        };
    }

    public int ProfileReplies => Replies.Count(reply => reply.Label == "profiles");

    public int ProfileTotal => Field(Replies.First(r => r.Label == "profiles").Json, "total");

    public int TotalFor(KbmLayout layout) =>
        Field(Replies.First(r => r.Label == $"map-{layout.Wire()}").Json, "total");

    /// <summary>Every source the corpus emitted for one layout's realized mapping.</summary>
    public IEnumerable<string> SourcesFor(KbmLayout layout)
    {
        foreach (var reply in Replies.Where(r => r.Label == $"map-{layout.Wire()}"))
        {
            using var document = JsonDocument.Parse(reply.Json);
            foreach (var binding in document.RootElement.GetProperty("bindings").EnumerateArray())
            {
                yield return binding.GetProperty("src").GetString()!;
            }
        }
    }

    public void Script(FakeTransportBase transport)
    {
        foreach (var reply in Replies)
        {
            transport.Replies[reply.Command] = reply.Json;
        }

        // The corpus covers only the commands ns2_kbm_commands.c formats. The
        // page's bootstrap also reads status, counters and mouse limits, which
        // come from the shared protocol fixture the three languages already
        // share.
        var protocol = ReadRepositoryFile("tools/fixtures/management/protocol-v1.json");
        using var document = JsonDocument.Parse(protocol);
        var vectors = document.RootElement.GetProperty("vectors");
        foreach (var name in new[] { "kbmStatus", "kbmCounters", "kbmMouse" })
        {
            var vector = vectors.GetProperty(name);
            transport.Replies[vector.GetProperty("command").GetString()!] =
                vector.GetProperty("reply").GetRawText();
        }
    }

    private static int Field(string json, string name)
    {
        using var document = JsonDocument.Parse(json);
        return document.RootElement.GetProperty(name).GetInt32();
    }

    // The fixtures are read from the repository rather than copied into the test
    // project: a copy is a second authority, and the point of tools/fixtures is
    // that C, C# and Kotlin read the same bytes.
    private static string ReadRepositoryFile(string relativePath)
    {
        var cursor = new DirectoryInfo(AppContext.BaseDirectory);
        while (cursor is not null)
        {
            var candidate = System.IO.Path.Combine(cursor.FullName, relativePath);
            if (File.Exists(candidate))
            {
                return File.ReadAllText(candidate);
            }

            cursor = cursor.Parent;
        }

        throw new FileNotFoundException(
            $"Cannot find {relativePath} above {AppContext.BaseDirectory}");
    }
}
