#ifndef DS5_AUDIO_TEST_TONE_H
#define DS5_AUDIO_TEST_TONE_H

#include <stdint.h>

#define DS5_AUDIO_TEST_TONE_FRAME_LEN 200u

// Two steady-state 10 ms, 48 kHz stereo Opus frames containing a loud 1 kHz
// tone. Generated by tools/generate_ds5_audio_tone.c with the same 160 kbit/s
// CBR/complexity-0 settings as the working reference. These are used only by
// the opt-in transport diagnostic; release builds do not enable it.
extern const uint8_t
    ds5_audio_test_tone_frames[2][DS5_AUDIO_TEST_TONE_FRAME_LEN];

#endif  // DS5_AUDIO_TEST_TONE_H
