#!/usr/bin/env python3
"""Harvest genuine catch-up length-0x28 PDUs into a C test fixture.

Why this exists
---------------
``ns2_motion_packet.py`` re-encodes every genuine 0x28 in the corpus byte for
byte, so the Python field map is validated against hardware. The firmware
packer is a second, independent implementation of the same map, and an
independent implementation is worth exactly nothing until it is held to the
same bar.

This emits the decoded fields Python recovered *plus* the genuine 40 bytes they
came from. The C test builds a packet from those fields and compares it to the
genuine bytes. Agreement means the firmware packer is byte-exact against real
hardware, not merely self-consistent -- a round trip against its own encoder
would prove nothing.

Catch-up only. That is the layout the translation path targets: its tail is a
single always-zero bit rather than a Q3 temperature pair a translated source
cannot produce (docs/experiments/pro2-carrier-unknown-fields-2026-07-31.md).

Regenerate:
    python tools/gen_motion40_fixture.py
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import ns2_motion_reference as R

ROOT = Path(__file__).resolve().parent.parent
DUMPS = ROOT / "dumps"
OUTPUT = ROOT / "tools" / "fixtures" / "ns2_motion40_catchup.h"


def captures():
    yield from sorted((DUMPS / "BLE CAPTURE").glob("*.jsonl"))
    yield from sorted((DUMPS / "motion").rglob("*.jsonl"))


def pdus_any(path, want_length):
    """Every PDU of one length in a capture, in order."""
    try:
        notifications, _ = R.read_motionpair_jsonl(path)
    except Exception:
        try:
            handles, _ = R.read_blecap_jsonl(path)
            notifications = max(handles.values(), key=len) if handles else []
        except Exception:
            return
    for notification in notifications:
        report = notification.value
        if len(report) <= 0x0E:
            continue
        length = report[0x0E]
        end = 0x0F + length
        if length == want_length and len(report) >= end:
            yield report[0x0F:end]


def pdus(path):
    try:
        notifications, _ = R.read_motionpair_jsonl(path)
    except Exception:
        try:
            handles, _ = R.read_blecap_jsonl(path)
            notifications = max(handles.values(), key=len) if handles else []
        except Exception:
            return
    for notification in notifications:
        report = notification.value
        if len(report) <= 0x0E:
            continue
        length = report[0x0E]
        end = 0x0F + length
        if length == 0x28 and len(report) >= end:
            yield report[0x0F:end]


def main() -> int:
    rows = []
    sources = set()
    for path in captures():
        for pdu in pdus(path):
            sample = R.decode_motion40(pdu, None)
            if sample.layout != "catchup":
                continue
            rows.append((sample, bytes(pdu)))
            sources.add(path.name)
    if not rows:
        print("no catch-up packets found", file=sys.stderr)
        return 2

    digest = hashlib.sha256()
    for _, pdu in rows:
        digest.update(pdu)

    lines = [
        "// GENERATED by tools/gen_motion40_fixture.py -- do not edit by hand.",
        "//",
        "// Genuine catch-up length-0x28 PDUs captured from a Nintendo Switch 2",
        "// Pro Controller 2, paired with the fields tools/ns2_motion_reference.py",
        "// decoded from them. That decoder re-encodes the whole corpus byte for",
        "// byte, so these fields are hardware-validated, not assumed.",
        "//",
        "// The C packer must rebuild `bytes` from `fields` exactly. A round trip",
        "// against its own encoder would prove nothing; this compares against",
        "// hardware through an independent implementation.",
        "//",
        f"// packets: {len(rows)}   captures: {len(sources)}",
        f"// sha256(concatenated PDUs): {digest.hexdigest()}",
        "",
        "#ifndef NS2_MOTION40_CATCHUP_FIXTURE_H",
        "#define NS2_MOTION40_CATCHUP_FIXTURE_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    uint16_t tick;",
        "    uint16_t elapsed_ticks;",
        "    uint8_t  status;",
        "    uint8_t  packing_mode;",
        "    uint8_t  tail_bit;",
        "    int32_t  carrier[3];",
        "    int32_t  accel[3][3];",
        "    int32_t  gyro[2][3];",
        "    uint8_t  bytes[40];",
        "} ns2_motion40_catchup_fixture_t;",
        "",
        f"#define NS2_MOTION40_CATCHUP_FIXTURE_COUNT {len(rows)}u",
        "",
        "static const ns2_motion40_catchup_fixture_t",
        "    ns2_motion40_catchup_fixtures[NS2_MOTION40_CATCHUP_FIXTURE_COUNT] = {",
    ]

    for sample, pdu in rows:
        accel = ", ".join(
            "{" + ", ".join(str(component) for component in vector) + "}"
            for vector in sample.accel
        )
        gyro = ", ".join(
            "{" + ", ".join(str(component) for component in vector) + "}"
            for vector in sample.gyro
        )
        carrier = ", ".join(str(value) for value in sample.prefix_carrier)
        data = ",".join(f"0x{byte:02X}" for byte in pdu)
        lines.append(
            f"    {{{sample.tick}, {sample.elapsed_ticks}, "
            f"0x{sample.sensor_status:02X}, {sample.packing_mode}, "
            f"{sample.tail_value}, {{{carrier}}}, {{{accel}}}, {{{gyro}}}, "
            f"{{{data}}}}},"
        )

    # The corpus is real motion, so it never approaches most slot limits. Two
    # implementations of the same bit map drift precisely where neither is
    # exercised -- sign extension at the negative edge, values that fill a
    # slot exactly, fields that straddle a byte boundary. These cases are built
    # by ns2_motion_packet.build_motion40, which is itself byte-exact over the
    # corpus above, so C is compared against a validated encoder rather than
    # against a hand-written expectation.
    import ns2_motion_packet as K

    def edge(width):
        limit = 1 << (width - 1)
        return (-limit, limit - 1, 0, -1, 1, limit // 2, -(limit // 2))

    edge_rows = []
    accel_widths, gyro_widths = (14, 13, 14), (16, 16)
    carrier_widths = (22, 21, 23)
    for index in range(7):
        fields = K.MotionPacketFields(
            tick=(0, 0xFFF, 1, 0x800, 0x7FF, 42, 4095)[index],
            elapsed_ticks=(15, 0xFFF, 16, 24, 100, 15, 4095)[index],
            carrier=tuple(edge(w)[index] for w in carrier_widths),
            accel=tuple(
                tuple(edge(w)[(index + axis) % 7] for axis in range(3))
                for w in accel_widths),
            gyro=tuple(
                tuple(edge(w)[(index + axis + 1) % 7] for axis in range(3))
                for w in gyro_widths),
            tail_value=index & 1,
            packing_mode=3,
        )
        edge_rows.append((fields, K.build_motion40(fields)))

    lines += [
        "};",
        "",
        "// Edge cases the corpus never reaches: slot limits, negative extremes,",
        "// and byte-straddling values. Expected bytes come from",
        "// tools/ns2_motion_packet.py, which is byte-exact over the corpus above.",
        "",
        f"#define NS2_MOTION40_CATCHUP_EDGE_COUNT {len(edge_rows)}u",
        "",
        "static const ns2_motion40_catchup_fixture_t",
        "    ns2_motion40_catchup_edges[NS2_MOTION40_CATCHUP_EDGE_COUNT] = {",
    ]
    for fields, pdu in edge_rows:
        accel = ", ".join(
            "{" + ", ".join(str(c) for c in vector) + "}" for vector in fields.accel)
        gyro = ", ".join(
            "{" + ", ".join(str(c) for c in vector) + "}" for vector in fields.gyro)
        carrier = ", ".join(str(v) for v in fields.carrier)
        data = ",".join(f"0x{byte:02X}" for byte in pdu)
        lines.append(
            f"    {{{fields.tick}, {fields.elapsed_ticks}, 0x0F, 3, "
            f"{fields.tail_value}, {{{carrier}}}, {{{accel}}}, {{{gyro}}}, "
            f"{{{data}}}}},")

    # The 0x28 prefix is a modular slice of the 0x1E carrier, not a copy: lane
    # 2 is centred half a window away and carries an extra bit, and the shift
    # is a floor rather than a truncation. Every one of those is somewhere a
    # C reimplementation can silently diverge -- especially the floor, since C
    # leaves right-shift of a negative value implementation-defined.
    #
    # Vectors are genuine carrier lanes taken from real 0x1E captures, plus
    # deliberate extremes, with expected output from ns2_motion_carrier.
    import ns2_motion_carrier as C

    carriers = []
    for path in captures():
        for pdu in pdus_any(path, 0x1E):
            orientation = R.decode_motion30_orientation(pdu)
            carriers.append(tuple(orientation.carrier_raw))
            if len(carriers) >= 24:
                break
        if len(carriers) >= 24:
            break
    carriers += [
        (0, 0, 0),
        ((1 << 26) - 1, (1 << 25) - 1, (1 << 24) - 1),
        (1 << 25, 1 << 24, 1 << 23),
        ((1 << 25) - 1, (1 << 24) - 1, (1 << 23) - 1),
        (1, 1, 1),
        ((1 << 25) + 1, (1 << 24) + 1, (1 << 23) + 1),
    ]

    lines += [
        "};",
        "",
        "// Carrier -> catch-up prefix slice. Expected values from",
        "// tools/ns2_motion_carrier.encode_prefix. Includes genuine carriers and",
        "// the field extremes, where a truncating shift diverges from a floor.",
        "",
        "typedef struct {",
        "    uint32_t carrier[3];",
        "    int32_t  prefix[3];",
        "} ns2_motion40_prefix_vector_t;",
        "",
        f"#define NS2_MOTION40_PREFIX_VECTOR_COUNT {len(carriers)}u",
        "",
        "static const ns2_motion40_prefix_vector_t",
        "    ns2_motion40_prefix_vectors[NS2_MOTION40_PREFIX_VECTOR_COUNT] = {",
    ]
    for raw in carriers:
        wire = C.encode_prefix(raw, False)
        lines.append(
            "    {{" + ", ".join(f"{v}u" for v in raw) + "}, {"
            + ", ".join(str(v) for v in wire) + "}},")

    lines += ["};", "", "#endif  // NS2_MOTION40_CATCHUP_FIXTURE_H", ""]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(rows)} packets "
          f"from {len(sources)} captures")
    print(f"sha256: {digest.hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
