#!/usr/bin/env python3
"""Embed web/index.html into a tiny read-only FAT12 disk image as a C header.

Usage: make_web_disk.py <input.html> <output.h>

The dongle serves this image over USB Mass Storage in config mode, so the config
page travels with the dongle. The script self-validates the generated image
(re-parses the BPB + FAT chain and extracts INDEX.HTM, comparing byte-for-byte)
and fails the build rather than ship a malformed disk.
"""
import struct
import sys

BPS = 512            # bytes per sector
SPC = 1              # sectors per cluster
RESERVED = 1         # reserved sectors (boot)
NFATS = 1
ROOT_ENTRIES = 16
SECTORS_PER_FAT = 1  # 512/1.5 = 341 entries, plenty for our cluster count


def fat12_set(fat, idx, val):
    off = idx + idx // 2
    if idx & 1:
        fat[off] = (fat[off] & 0x0F) | ((val << 4) & 0xF0)
        fat[off + 1] = (val >> 4) & 0xFF
    else:
        fat[off] = val & 0xFF
        fat[off + 1] = (fat[off + 1] & 0xF0) | ((val >> 8) & 0x0F)


def fat12_get(fat, idx):
    off = idx + idx // 2
    if idx & 1:
        return ((fat[off] >> 4) & 0x0F) | (fat[off + 1] << 4)
    return fat[off] | ((fat[off + 1] & 0x0F) << 8)


def build(html):
    root_sectors = (ROOT_ENTRIES * 32 + BPS - 1) // BPS
    data_start = RESERVED + NFATS * SECTORS_PER_FAT + root_sectors

    data_needed = max(1, (len(html) + BPS - 1) // BPS)
    total_sectors = max(64, data_start + data_needed + 8)  # headroom for growth
    data_sectors = total_sectors - data_start

    boot = bytearray(BPS)
    boot[0:3] = b"\xEB\x3C\x90"
    boot[3:11] = b"MSDOS5.0"
    struct.pack_into("<H", boot, 11, BPS)
    boot[13] = SPC
    struct.pack_into("<H", boot, 14, RESERVED)
    boot[16] = NFATS
    struct.pack_into("<H", boot, 17, ROOT_ENTRIES)
    struct.pack_into("<H", boot, 19, total_sectors)
    boot[21] = 0xF8
    struct.pack_into("<H", boot, 22, SECTORS_PER_FAT)
    struct.pack_into("<H", boot, 24, 1)   # sectors per track
    struct.pack_into("<H", boot, 26, 1)   # heads
    boot[36] = 0x80                        # drive number
    boot[38] = 0x29                        # extended boot signature
    struct.pack_into("<I", boot, 39, 0x50535731)  # volume id
    boot[43:54] = b"PICOSWITCH "
    boot[54:62] = b"FAT12   "
    boot[510] = 0x55
    boot[511] = 0xAA

    nclusters = max(1, (len(html) + BPS * SPC - 1) // (BPS * SPC))
    fat = bytearray(SECTORS_PER_FAT * BPS)
    fat12_set(fat, 0, 0xFF8)
    fat12_set(fat, 1, 0xFFF)
    first = 2
    for i in range(nclusters):
        c = first + i
        fat12_set(fat, c, 0xFFF if i == nclusters - 1 else c + 1)

    root = bytearray(root_sectors * BPS)
    root[0:11] = b"PICOSWITCH "
    root[11] = 0x08  # volume label
    e = 32
    root[e:e + 11] = b"INDEX   HTM"
    root[e + 11] = 0x20  # archive
    struct.pack_into("<H", root, e + 26, first)       # start cluster
    struct.pack_into("<I", root, e + 28, len(html))   # file size

    data = bytearray(data_sectors * BPS)
    data[0:len(html)] = html

    image = bytes(boot + fat + root + data)
    assert len(image) == total_sectors * BPS
    return image, total_sectors, data_start


def validate(image, total_sectors, data_start, html):
    assert struct.unpack_from("<H", image, 11)[0] == BPS
    root_off = (RESERVED + NFATS * SECTORS_PER_FAT) * BPS
    entry = None
    for i in range(ROOT_ENTRIES):
        ent = image[root_off + i * 32: root_off + i * 32 + 32]
        if ent[0:11] == b"INDEX   HTM":
            entry = (struct.unpack_from("<H", ent, 26)[0], struct.unpack_from("<I", ent, 28)[0])
    assert entry, "INDEX.HTM not in root directory"
    start, size = entry
    assert size == len(html), "size mismatch"

    fat = image[RESERVED * BPS: RESERVED * BPS + SECTORS_PER_FAT * BPS]
    out = bytearray()
    c = start
    guard = 0
    while c < 0xFF8:
        sec = data_start + (c - 2) * SPC
        out += image[sec * BPS: sec * BPS + BPS * SPC]
        c = fat12_get(fat, c)
        guard += 1
        assert guard < total_sectors, "FAT chain loop"
    assert bytes(out[:size]) == html, "extracted file does not match source"


def main():
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "rb") as f:
        html = f.read()
    image, total_sectors, data_start = build(html)
    validate(image, total_sectors, data_start, html)
    with open(dst, "w") as f:
        f.write("// Auto-generated by tools/make_web_disk.py from web/index.html. Do not edit.\n")
        f.write("#ifndef _WEB_DISK_H_\n#define _WEB_DISK_H_\n#include <stdint.h>\n")
        f.write(f"#define WEB_DISK_BLOCK_SIZE {BPS}\n")
        f.write(f"#define WEB_DISK_NUM_BLOCKS {total_sectors}\n")
        f.write("static const uint8_t web_disk[] = {\n")
        for i in range(0, len(image), 16):
            f.write("  " + ",".join(str(b) for b in image[i:i + 16]) + ",\n")
        f.write("};\n#endif  // _WEB_DISK_H_\n")
    print(f"OK: html={len(html)}B image={len(image)}B sectors={total_sectors} clusters validated")


if __name__ == "__main__":
    main()
