// USB Mass Storage callbacks: a small read-only FAT12 disk that carries the
// configuration web page (index.html), so the dongle is self-contained. Active
// only in configuration mode (the MSC interface only exists in that config
// descriptor). The disk image is generated by tools/make_web_disk.py.

#include <string.h>

#include "tusb.h"

#include "web_disk.h"

void tud_msc_inquiry_cb(uint8_t lun, uint8_t vendor_id[8], uint8_t product_id[16], uint8_t product_rev[4]) {
    (void)lun;
    memcpy(vendor_id, "PicoSw  ", 8);
    memcpy(product_id, "Config Disk     ", 16);
    memcpy(product_rev, "1.0 ", 4);
}

bool tud_msc_test_unit_ready_cb(uint8_t lun) {
    (void)lun;
    return true;
}

void tud_msc_capacity_cb(uint8_t lun, uint32_t *block_count, uint16_t *block_size) {
    (void)lun;
    *block_count = WEB_DISK_NUM_BLOCKS;
    *block_size = WEB_DISK_BLOCK_SIZE;
}

bool tud_msc_start_stop_cb(uint8_t lun, uint8_t power_condition, bool start, bool load_eject) {
    (void)lun;
    (void)power_condition;
    (void)start;
    (void)load_eject;
    return true;
}

bool tud_msc_is_writable_cb(uint8_t lun) {
    (void)lun;
    return false;  // read-only
}

int32_t tud_msc_read10_cb(uint8_t lun, uint32_t lba, uint32_t offset, void *buffer, uint32_t bufsize) {
    (void)lun;
    if (lba >= WEB_DISK_NUM_BLOCKS)
        return -1;

    uint32_t addr = lba * WEB_DISK_BLOCK_SIZE + offset;
    uint32_t avail = (addr < sizeof(web_disk)) ? (sizeof(web_disk) - addr) : 0;
    uint32_t n = bufsize < avail ? bufsize : avail;

    if (n)
        memcpy(buffer, web_disk + addr, n);
    if (n < bufsize)
        memset((uint8_t *)buffer + n, 0, bufsize - n);
    return (int32_t)bufsize;
}

int32_t tud_msc_write10_cb(uint8_t lun, uint32_t lba, uint32_t offset, uint8_t *buffer, uint32_t bufsize) {
    (void)lun;
    (void)lba;
    (void)offset;
    (void)buffer;
    (void)bufsize;
    return -1;  // read-only: reject writes
}

int32_t tud_msc_scsi_cb(uint8_t lun, uint8_t const scsi_cmd[16], void *buffer, uint16_t bufsize) {
    (void)buffer;
    (void)bufsize;
    switch (scsi_cmd[0]) {
        case SCSI_CMD_PREVENT_ALLOW_MEDIUM_REMOVAL:
            return 0;  // nothing to do, succeed
        default:
            tud_msc_set_sense(lun, SCSI_SENSE_ILLEGAL_REQUEST, 0x20, 0x00);
            return -1;
    }
}
